sudo: required

services: 
    - docker

before_install:
    - docker build -t nagameena/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nagameena/docker-react npm run test -- --coverage